### ISSUE TITLE
Python: Operation BandpassFilter ignores denominator polynom

### ISSUE THREAD

**Issue by LnnrtS** [us4useu/arrus#279]
https://github.com/us4useu/arrus/blob/d7b373241f6bea3f623caa7f2b84f7305c5da554/api/python/arrus/utils/imaging.py#L642-L646

calculates filter coefficients for a butterworth IIR filter but only nominator polynom is used for convolution 

https://github.com/us4useu/arrus/blob/d7b373241f6bea3f623caa7f2b84f7305c5da554/api/python/arrus/utils/imaging.py#L650-L652

Generally, this is only possible if the denominator polynom is 1.0 (which is not the case here).

As far as I have seen cupy cannot accelerate IIR filters (at the moment) so probably the filtertaps could be generated with `scipy.signal.firwin` ?

**Comment by LnnrtS** [comment]
@pjarosik Looks this is fixed from 0.8.0 on..?

**Comment by pjarosik** [comment]
@LnnrtS yes, it's fixed since v0.8.0. Now BandpassFilter uses the proper FIR coefficients by default.
NOTE:
- starting from v 13.0.0 cupy suports IIR filters (see e.g [cuypx.scipy.signal.filtfilt](https://docs.cupy.dev/en/latest/reference/generated/cupyx.scipy.signal.filtfilt.html) function)
- you can also use the [FirFilter op](https://us4useu.github.io/arrus-docs/releases/v0.9.2/python/content/api.html#arrus.utils.imaging.FirFilter) instead of BandpassFilter
